# Generated by Django 4.2.11 on 2024-05-31 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name': 'Variations', 'verbose_name_plural': 'Variations'},
        ),
    ]
